version: '2'
services:
    trustloot-app:
        image: trustloot
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://trustloot-mysql:3306/trustloot?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trustloot-mysql:
        extends:
            file: mysql.yml
            service: trustloot-mysql
